### ISSUE TITLE
可视化

### ISSUE THREAD

**Issue by Dx3281101** [Vitalitypi/MSTAGNN#1]
![image](https://github.com/user-attachments/assets/0b818e3a-5f96-4182-9731-1ad8d606e305)
您好，能分享一下这部分如何做到的吗，感谢！

**Comment by Vitalitypi** [comment]
您好，提取PEMSD3数据集272节点在两个模型相应时刻的预测结果以及真实值就行了

**Comment by Dx3281101** [comment]
好的，谢谢
